spring:
  application:
    name: rosey
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    jdbcUrl: jdbc:hsqldb:hsql://localhost/rosey
    username: sa
    password:
  main:
    web-application-type: none
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    root: ERROR